trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v2.1.0

jobs:
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py37]
    os: windows
    pre_test:
    - task: UseRubyVersion@0
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH
    - powershell: |
        Write-Host "##vso[task.prependpath]C:\Strawberry\perl\bin"
        Write-Host "##vso[task.prependpath]C:\Strawberry\perl\site\bin"
        Write-Host "##vso[task.prependpath]C:\Strawberry\c\bin"
      displayName: Add strawberry perl to PATH
    - bash: testing/get-dart.sh
      displayName: install dart
    - powershell: testing/get-r.ps1
      displayName: install R
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py37]
    os: linux
    name_postfix: _latest_git
    pre_test:
    - task: UseRubyVersion@0
    - template: step--git-install.yml
    - bash: testing/get-coursier.sh
      displayName: install coursier
    - bash: testing/get-dart.sh
      displayName: install dart
    - bash: testing/get-swift.sh
      displayName: install swift
    - bash: testing/get-r.sh
      displayName: install R
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy3, py36, py37, py38, py39]
    os: linux
    pre_test:
    - task: UseRubyVersion@0
    - bash: testing/get-coursier.sh
      displayName: install coursier
    - bash: testing/get-dart.sh
      displayName: install dart
    - bash: testing/get-swift.sh
      displayName: install swift
    - bash: testing/get-r.sh
      displayName: install R
