# real world
-   id: hello-world
    name: Say hi
    entry: Rscript hello-world.R
    args: [blibla]
    language: r
    types: [r]
-   id: hello-world-inline
    name: Say hi
    entry: |
      Rscript -e
      'stopifnot(
        packageVersion("rprojroot") == "1.0",
        packageVersion("gli.clu") == "0.0.0.9000"
      )
      cat(commandArgs(trailingOnly = TRUE), "from R!\n", sep = ", ")
      '
    args: ['Hi-there']
    language: r
    types: [r]
-   id: additional-deps
    name: Check additional deps
    entry: Rscript additional-deps.R
    language: r
    types: [r]
